# Generated by Django 4.2.4 on 2023-08-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('seats', models.IntegerField(default=2)),
                ('color', models.CharField(max_length=30)),
                ('vin', models.CharField(blank=True, max_length=30)),
                ('current_mileage', models.IntegerField(default=0)),
                ('service_interval', models.IntegerField(blank=True, default=0)),
                ('next_service', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['make', 'year'],
                'abstract': False,
            },
        ),
    ]
