# Generated by Django 4.2.4 on 2023-08-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_truck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('service_interval', models.IntegerField(blank=True, default=0)),
                ('next_service', models.DateTimeField(auto_now_add=True, null=True)),
                ('length', models.IntegerField(default=10)),
                ('width', models.IntegerField(default=10)),
                ('hin', models.CharField(blank=True, max_length=30)),
                ('current_hours', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['make', 'year'],
                'abstract': False,
            },
        ),
    ]
